# Generated by Django 4.1.6 on 2024-07-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('AirlineID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Headquarters', models.CharField(max_length=30)),
                ('ContactNumber', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('FlightID', models.IntegerField(primary_key=True, serialize=False)),
                ('FlightNumber', models.IntegerField(max_length=30)),
                ('DepartureAirport', models.CharField(max_length=30)),
                ('ArrivalAirport', models.CharField(max_length=30)),
                ('AirlineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_app.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('PassengerID', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ReservationID', models.IntegerField(primary_key=True, serialize=False)),
                ('Class', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('FlightID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_app.flight')),
                ('PassengerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_app.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('TicketID', models.IntegerField(primary_key=True, serialize=False)),
                ('PaymentStatus', models.CharField(max_length=30)),
                ('ReservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_app.reservation')),
            ],
        ),
    ]
