# Generated by Django 4.1.6 on 2024-07-03 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='ArrivalTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='flight',
            name='AvailableSeats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='DepartureTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='flight',
            name='Duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='flight',
            name='TotalSeats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='PassportID',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='passenger',
            name='dob',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ReservationDate',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='SeatNumber',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='ticket',
            name='Fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='IssueDate',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='airline',
            name='AirlineID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airline',
            name='ContactNumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='airline',
            name='Headquarters',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airline',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ArrivalAirport',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DepartureAirport',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='FlightID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='FlightNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='PassengerID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Class',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ReservationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Checked-in', 'Checked-in')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='PaymentStatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='TicketID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
