# Generated by Django 4.1.6 on 2024-07-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0002_flight_arrivaltime_flight_availableseats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='phone_no',
            new_name='phoneNumber',
        ),
    ]
