# Generated by Django 4.1.6 on 2024-07-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0003_rename_first_name_passenger_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='Duration',
        ),
    ]
